In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [13]:
data = fetch_california_housing()
X = pd.DataFrame(data=data.data , columns=data.feature_names)
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [19]:
y = pd.DataFrame(data.target , columns=data.target_names)
y.head()

   MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

In [21]:
print(X.isnull().sum().sum())
print(y.isnull().sum())

0
MedHouseVal    0
dtype: int64

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

### ridge regression pipeline

In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge_pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('model',Ridge())
])

ridge_params = {
    'model__alpha':[0.01, 0.1, 1, 10, 100],
    'model__solver':['auto', 'saga']
}

ridge_grid = GridSearchCV(ridge_pipeline,ridge_params,cv=5)

ridge_grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Ridge())]),
             param_grid={'model__alpha': [0.01, 0.1, 1, 10, 100],
                         'model__solver': ['auto', 'saga']})

In [40]:
best_ridge_model = ridge_grid.best_estimator_
ridge_y_pred = best_ridge_model.predict(X_test)

In [41]:
# accuracy 
from sklearn.metrics import mean_squared_error , r2_score

print("ridge RMSE score ",np.sqrt(mean_squared_error(y_test, ridge_y_pred)))
print("ridge r2 score ",r2_score(y_test, ridge_y_pred))

ridge RMSE score  0.7455811358288166
ridge r2 score  0.5757879873121599

### lasso regression

In [43]:
from sklearn.linear_model import Lasso

lasso_pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('lasso_model',Lasso())
])

lasso_params = {
    'lasso_model__alpha':[0.01, 0.1, 1, 10, 100],
    'lasso_model__selection': ['cyclic', 'random']
}
lasso_grid = GridSearchCV(lasso_pipeline , lasso_params, cv= 5)

lasso_grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('lasso_model', Lasso())]),
             param_grid={'lasso_model__alpha': [0.01, 0.1, 1, 10, 100],
                         'lasso_model__selection': ['cyclic', 'random']})

In [45]:
best_lasso_model = lasso_grid.best_estimator_
lasso_y_pred = best_lasso_model.predict(X_test)

In [ ]:
print("lasso RMSE score ",np.sqrt(mean_squared_error(y_test, lasso_y_pred)))
print("lasso r2 score ",r2_score(y_test, lasso_y_pred))

ridge RMSE score  0.7404423656125414
ridge r2 score  0.5816154300698727

### Elastic Net

In [49]:
from sklearn.linear_model import ElasticNet
elastic_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('elastic_model',ElasticNet(max_iter=10000, tol=1e-4))
])

elastic_params = {
    'elastic_model__alpha' : [0.01,0.1,1,2,3,5,10],
    'elastic_model__l1_ratio':[0.1,0.2,0.3,0.5,0.6,0.8,0.9,1],  # Avoid 0 to prevent Ridge warning
    'elastic_model__max_iter':[1000,2000,5000]
}

elastic_grid = GridSearchCV(elastic_pipeline, elastic_params , cv=5)

elastic_grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('elastic_model',
                                        ElasticNet(max_iter=10000))]),
             param_grid={'elastic_model__alpha': [0.01, 0.1, 1, 2, 3, 5, 10],
                         'elastic_model__l1_ratio': [0.1, 0.2, 0.3, 0.5, 0.6,
                                                     0.8, 0.9, 1],
                         'elastic_model__max_iter': [1000, 2000, 5000]})

In [52]:
best_elastic_model = elastic_grid.best_estimator_
elastic_y_pred = best_elastic_model.predict(X_test)

print("ElasticNet RMSE:", np.sqrt(mean_squared_error(y_test, elastic_y_pred)))
print("ElasticNet R2:", r2_score(y_test, elastic_y_pred))

ElasticNet RMSE: 0.7429021059509155
ElasticNet R2: 0.5788310762589679

In [53]:
models = {
    "Ridge": best_ridge_model,
    "Lasso": best_lasso_model,
    "ElasticNet": best_elastic_model
}

for name, model in models.items():
    preds = model.predict(X_test)
    print(name, "R2:", r2_score(y_test, preds))

Ridge R2: 0.5757879873121599
Lasso R2: 0.5816154300698727
ElasticNet R2: 0.5788310762589679

In [55]:
coef = best_lasso_model.named_steps["lasso_model"].coef_

for feature, weight in zip(X.columns, coef):
    print(feature, weight)

MedInc 0.8009574381665312
HouseAge 0.12708700893832975
AveRooms -0.16275931275537522
AveBedrms 0.2062074531361803
Population -0.0
AveOccup -0.030601761642690087
Latitude -0.7901125382833238
Longitude -0.7556737928328278